

#include "..\Target\Target.h"
#include "..\CortexM4\CortexM4_NVIC_Def.h"


void CortexM4NvicInit(void) {
	volatile sCORTEX_M4_NVIC* pCORTEX_M4_NVIC = (sCORTEX_M4_NVIC *)CORTEX_M4_NVIC_ADR;
	uCORTEX_M4_NVIC_ISER0 CORTEX_M4_NVIC_ISER0;
	uCORTEX_M4_NVIC_ISER1 CORTEX_M4_NVIC_ISER1;
	uCORTEX_M4_NVIC_ISER2 CORTEX_M4_NVIC_ISER2;

	CORTEX_M4_NVIC_ISER0.All = CORTEX_M4_NVIC_ISER0_RESET_VALUE;
	CORTEX_M4_NVIC_ISER0.All = 0xFFFFFFFF;
	pCORTEX_M4_NVIC->CORTEX_M4_NVIC_ISER0.All = CORTEX_M4_NVIC_ISER0.All;

	CORTEX_M4_NVIC_ISER1.All = CORTEX_M4_NVIC_ISER1_RESET_VALUE;
	CORTEX_M4_NVIC_ISER1.All = 0xFFFFFFFF;
	pCORTEX_M4_NVIC->CORTEX_M4_NVIC_ISER1.All = CORTEX_M4_NVIC_ISER1.All;

	CORTEX_M4_NVIC_ISER2.All = CORTEX_M4_NVIC_ISER2_RESET_VALUE;
	CORTEX_M4_NVIC_ISER2.All = 0xFFFFFFFF;
	pCORTEX_M4_NVIC->CORTEX_M4_NVIC_ISER2.All = CORTEX_M4_NVIC_ISER2.All;
}

